
# Created empty volume in a pod and both containers inside pod are sharing same volume .




apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp

  template:
    metadata:
      labels:
        app: myapp

    spec:
      volumes:
      - name:  cache
        emptyDir: {}
      containers:
      - name: one
        image: nginx  
        command:
         - "bin/sh"
        args:
         - "-c"
         - "touch /boo/bar.txt && sleep  3600"  
        volumeMounts:
          - name:  cache
            mountPath:  /boo

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: two
        image: nginx  
        command:
         - "bin/sh"
        args:
         - "-c"
         - "touch bo/bow.txt && sleep  3600"  
        volumeMounts:
          - name:  cache
            mountPath:  /bo

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        
